### PR TITLE
APIGOV-21478 Remove UpdateFromAPIServer cfg value

### PR DESCRIPTION
**Pull request by tsjohns9**
- Remove the UpdateFromAPIServer config value
- Exported functions to get API's by attributes in discovery.go will only check the sdk cache

### CODE REVIEW

**Comment by tsjohns9** [comment]
Is there documentation that needs to be changed since I removed a config value?

**Review by sbolosan — APPROVED** [review]
Looks like there was docs associated with the original ticket... let me look

**Comment by sbolosan** [comment]
@tsjohns9 , maybe not...  I only see api server reference to version and pattern stuff I did... @jcollins-axway did the original PT-SMI ticket, maybe he can shed some light on doc stuff, but as I see it, I don't see anything for pathUpdateFromAPIServer

**Comment by jcollins-axway** [comment]
> @tsjohns9 , maybe not... I only see api server reference to version and pattern stuff I did... @jcollins-axway did the original PT-SMI ticket, maybe he can shed some light on doc stuff, but as I see it, I don't see anything for pathUpdateFromAPIServer

This was never a published option, so no docs to update

**Review by jcollins-axway — APPROVED** [review]

**Pull request merged**
